name: 'Government URLs'
description: 'An inventory of all the government domains outside the .gov and .mil top-level domains. '
license: null
openSourceProject: 1
governmentWideReuseProject: 0
tags:
    - GSA
    - Search.gov
    - domains
    - websites
contact:
    email: search@gsa.gov
